name: release PR validation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    permissions:
      contents: read
    uses: ./.github/workflows/build-release.yml
    with:
      version: ""
      publish: false
      prerelease: false
      ref: ${{ github.sha }}
