name: release validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  validate:
    permissions:
      contents: read
    uses: ./.github/workflows/build-release.yml
    with:
      version: ""
      publish: false
      prerelease: false
      ref: ${{ github.sha }}
